#
# Working with files in Github WOrkflows
# List files in a specific directory
#
name: Files Work 03.6.5

run-name: ${{github.actor}} trig ${{github.workflow}}

on:
  push:
    branches: [ main ]
    paths: ['**.pdf' , '**.DOC']

# accept a manual run from the app or from http.
  workflow_dispatch:
      inputs:
          run_zowe:
              description: 'Run ZOWE?'
              required: false
              default: 'N'
              type: choice
              options:
                    - 'Y'
                    - 'N'

          pds_name:
              description: 'PDS name?'
              required: false
              default: 'CBL'
              
  repository_dispatch:
   
jobs:
  gwf-mf-list01:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
 #         working-directory: ./scripts
    
    steps:
    - uses: actions/checkout@v4
      timeout-minutes: 1
    
    - name: gwf_name01
      run: |
         echo "Hi World"
         echo "Param=${{github.event.inputs.run_zowe}}"
         echo "Param=${{github.event.inputs.pds_name}}"
         echo "user=${{secrets.ZOWE_USERNAME}}"

    - name: check_default
      run: |
          echo "$(pwd)"
          echo $PATH
          echo $GITHUB_PATH

    - name: listFile0
      run: ls -l
    
# display the location where global installs are put
    - name: zowe dir
      run: |
             cd .github/.zowe
             ls -l

    - name: createFile
      run: touch testzow.dat

    - name: modFile
      run: echo "Some data" > testzow.dat

    - name: check_default2
      run: echo "$(pwd)"

    - name: listFile
      run: ls -l

    - name: cd_chk
      run: cd testDir

    - name: check_default3
      run: echo "$(pwd)"

    - name: listFile2
      run: ls -l

    - name: cleanup
      run: echo "Job done"
      
#***************************************************
